language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - ANDROID_API_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_EMU_API_LEVEL=26
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ANDROID_EMU_IMG="system-images;android-${ANDROID_EMU_API_LEVEL};${ANDROID_TAG};${ANDROID_ABI}"
    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"
    - ANDROID_HOME=/usr/local/android-sdk-26.0.2
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - QEMU_AUDIO_DRV=none
    - ADB_INSTALL_TIMEOUT=20

android:
  components: 
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    - extra-android-support
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
    - extra-google-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
    
before_cache:
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock # Avoid to repack it due locks
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/classAnalysis/classAnalysis.lock
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/jarSnapshots/jarSnapshots.lock

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

notifications:
  email: false

install:
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-${ANDROID_API_LEVEL}" # Latest platform required by SDK tools
  - echo yes | sdkmanager "platforms;android-${ANDROID_EMU_API_LEVEL}" # Android platform required by emulator
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "${ANDROID_EMU_IMG}" # Install emulator system image
  - echo no | avdmanager create avd --force -n test -k ${ANDROID_EMU_IMG} --abi ${ANDROID_ABI} --tag ${ANDROID_TAG}
  - emulator -avd test -no-window &
  
before_script:
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - sleep 30
  - adb shell input keyevent 82 &
  - sleep 15

script:
  - ./gradlew connectedAndroidTest -PdisablePreDex
