language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - ANDROID_API_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.3
    - ANDROID_EMU_API_LEVEL=23
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ANDROID_EMU_IMG="system-images;android-${ANDROID_EMU_API_LEVEL};${ANDROID_TAG};${ANDROID_ABI}"
    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - QEMU_AUDIO_DRV=none
    - ADB_INSTALL_TIMEOUT=20

android:
  components: 
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    - extra-android-support
    - sys-img-$ANDROID_ABI-$ANDROID_TAG-$ANDROID_EMU_API_LEVEL
    - extra-google-m2repository  

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

notifications:
  email: false
  
before_cache:
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock # Avoid to repack it due locks
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/classAnalysis/classAnalysis.lock
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/jarSnapshots/jarSnapshots.lock

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
  
before_install:
  - chmod +x gradlew
  - echo 'count=0' > /home/travis/.android/repositories.cfg

install:
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo no | avdmanager create avd --force -n test -k ${ANDROID_EMU_IMG} --abi ${ANDROID_ABI} --tag ${ANDROID_TAG}
  - emulator -avd test -no-window -camera-back none -camera-front none &
  
before_script:
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - sleep 30
  - adb shell input keyevent 82 &
  - sleep 15

script:
  - travis_wait 30 ./gradlew :sample:connectedAndroidTest -PdisablePreDex
