language: android
jdk: oraclejdk8
sudo: required
env:
  global:
    - ANDROID_API_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_EMU_API_LEVEL=21
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - QEMU_AUDIO_DRV=none
    - ADB_INSTALL_TIMEOUT=20
android:
  components: 
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    - extra-android-support
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
    - extra-google-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
    
before_script:
    - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
    - emulator -avd test -engine classic -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - ./gradlew connectedAndroidTest
